
services:
  services-api:
    build:
      context: ./
      dockerfile: Dockerfile
    env_file: ".env"
    ports:
      - "${EXTERNAL_SERVICES_API_PORT}:${SERVICES_API_PORT}"
    volumes:
      - ./src:/app/src
    restart: unless-stopped
    depends_on:
      - db_container

  db_container:
    image: postgres:13
    env_file: ".env"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    container_name: db_container

  tests:
    build:
      context: ./
      dockerfile: Dockerfile  # Usa el mismo Dockerfile o un Dockerfile de test específico
    env_file: ".env"
    depends_on:
      - db_container
    command: ["pytest", "/app/tests"] 