FROM python:3.10.12-slim

WORKDIR /app

COPY requirements.txt /app/
RUN pip install --no-cache-dir --upgrade -r /app/requirements.txt

COPY ./src /app/src
COPY ./tests /app/tests
ENV PYTHONPATH=/app/src

CMD ["pytest", "/app/tests"]