FROM python:3.10.12-slim

WORKDIR /app


COPY requirements.txt /app/
COPY requirements-tests.txt /app/

RUN ls -l /app/
RUN pip install --no-cache-dir --upgrade -r /app/requirements-tests.txt
RUN pip list


COPY ./src /app/src
COPY ./tests /app/tests
ENV PYTHONPATH=/app/src

CMD ["sh", "-c", "pytest --cov=/app/src --cov-report=term-missing /app/tests"]
