services:
  tests:
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - .env.test
    depends_on:
      test_db_container:
        condition: service_healthy
    command: ["pytest", "/app/tests"]
    networks:
      - test_network

  test_db_container:
    image: postgres:13
    env_file:
      - .env.test
    ports:
      - 5432:5432
    networks:
      - test_network
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB} -h $${POSTGRES_HOST}",
        ]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  test_network:
    driver: bridge
