services:
  services-api:
    build:
      context: ./
      dockerfile: Dockerfile
    env_file: ".env"
    ports:
      - "${SERVICES_API_PORT}:9212"
    volumes:
      - ./src:/app/src
    restart: unless-stopped
    depends_on:
      db_container:
        condition: service_healthy

  db_container:
    image: postgres:13
    env_file: ".env"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
      RAILWAY_RUN_UID: 0
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    container_name: db_container
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB} -h $${POSTGRES_HOST}",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
