name: CI - Tests

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  test:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: read

    services:
      postgres:
        image: postgres:13
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password_ps
          POSTGRES_DB: test_db
    env:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password_ps
      POSTGRES_DB: test_db
      POSTGRES_PORT: 5432
      POSTGRES_HOST: localhost
      ENV: test
      API_KEY: 123
      API_SERVICE_MANAGER: http://localhost:4006/

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-tests.txt
      - name: Wait for Postgres
        run: |
          echo "Waiting for Postgres to be ready..."
          until nc -z localhost 5432; do
            echo "Waiting for Postgres to start..."
            sleep 5
          done
      - name: Run tests
        env:
          PYTHONPATH: ./src
          DATABASE_URL: postgresql://postgres:password_ps@localhost:5432/test_db
        run: |
          pytest --cov --cov-report=xml
      - name: Report Coverage
        env:
          PYTHONPATH: ./src
        run: |
          pip install coverage
          coverage run -m pytest
          coverage report
          coverage xml
      - name: Upload coverage to Codecov
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN}}
        run: |
          bash <(curl -s https://codecov.io/bash)
